-- MySQL Script generated by MySQL Workbench
-- Wed Feb 21 00:19:48 2024
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Branch` ;

CREATE TABLE IF NOT EXISTS `Branch` (
  `BranchId` INT NOT NULL AUTO_INCREMENT,
  `BranchState` CHAR(2) NOT NULL,
  `BranchCity` VARCHAR(50) NOT NULL,
  `BranchAddress` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`BranchId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manager` ;

CREATE TABLE IF NOT EXISTS `Manager` (
  `ManagerId` INT NOT NULL AUTO_INCREMENT,
  `ManagerName` VARCHAR(60) NOT NULL,
  `ManagerTaxId` VARCHAR(45) NOT NULL,
  `DirectManagerId` INT NULL,
  `BranchId` INT NOT NULL,
  PRIMARY KEY (`ManagerId`),
  INDEX `fk_Manager_Direct_idx` (`DirectManagerId` ASC) VISIBLE,
  INDEX `fk_Manager_Branch1_idx` (`BranchId` ASC) VISIBLE,
  CONSTRAINT `fk_Manager_Direct`
    FOREIGN KEY (`DirectManagerId`)
    REFERENCES `Manager` (`ManagerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Manager_Branch1`
    FOREIGN KEY (`BranchId`)
    REFERENCES `Branch` (`BranchId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `AccountId` INT NOT NULL AUTO_INCREMENT,
  `AccountOpenDate` DATE NOT NULL,
  `AccountCloseDate` DATE NULL,
  `AccountStatus` CHAR(1) NOT NULL,
  `ManagerId` INT NOT NULL,
  `AccountBalance` DECIMAL(17,2) NULL,
  `AccountLimit` DECIMAL(17,2) NULL,
  PRIMARY KEY (`AccountId`),
  INDEX `fk_Account_Manager_idx` (`ManagerId` ASC) VISIBLE,
  CONSTRAINT `fk_Account_Manager`
    FOREIGN KEY (`ManagerId`)
    REFERENCES `Manager` (`ManagerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customer` ;

CREATE TABLE IF NOT EXISTS `Customer` (
  `CustomerId` INT NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(60) NOT NULL,
  `CustomerBirthDate` DATE NOT NULL,
  `CustomerPhoneNumber` VARCHAR(50) NULL,
  `CustomerEmail` VARCHAR(200) NULL,
  PRIMARY KEY (`CustomerId`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `CustomerAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CustomerAccount` ;

CREATE TABLE IF NOT EXISTS `CustomerAccount` (
  `CustomerAccountId` INT NOT NULL AUTO_INCREMENT,
  `AccountId` INT NOT NULL,
  `CustomerId` INT NOT NULL,
  `RelationalStatus` CHAR(1) NULL,
  `RelationalOpenDate` DATE NULL,
  `RelationalCloseDate` DATE NULL,
  INDEX `fk_CustomerAccount_Customer_idx` (`CustomerId` ASC) VISIBLE,
  INDEX `fk_CustomerAccount_Account_idx` (`AccountId` ASC) VISIBLE,
  PRIMARY KEY (`CustomerAccountId`),
  CONSTRAINT `fk_CustomerAccount_Customer`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CustomerAccount_Account`
    FOREIGN KEY (`AccountId`)
    REFERENCES `Account` (`AccountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `CustomerAccountBranch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CustomerAccountBranch` ;

CREATE TABLE IF NOT EXISTS `CustomerAccountBranch` (
  `CustomerAccountBranchId` INT NOT NULL AUTO_INCREMENT,
  `BranchId` INT NOT NULL,
  `CustomerAccountId` INT NOT NULL,
  INDEX `fk_CustomerAccountBranch_Branch_idx` (`BranchId` ASC) VISIBLE,
  PRIMARY KEY (`CustomerAccountBranchId`),
  INDEX `fk_CustomerAccountBranch_CustomerAccount_idx` (`CustomerAccountId` ASC) VISIBLE,
  CONSTRAINT `fk_CustomerAccountBranch_Branch`
    FOREIGN KEY (`BranchId`)
    REFERENCES `Branch` (`BranchId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CustomerAccountBranch_CustomerAccount`
    FOREIGN KEY (`CustomerAccountId`)
    REFERENCES `CustomerAccount` (`CustomerAccountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TransactionType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransactionType` ;

CREATE TABLE IF NOT EXISTS `TransactionType` (
  `TransactionTypeId` INT NOT NULL AUTO_INCREMENT,
  `TransactionTypeDescription` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TransactionTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transaction` ;

CREATE TABLE IF NOT EXISTS `Transaction` (
  `TransactionNr` BIGINT NOT NULL AUTO_INCREMENT,
  `TransactiontDate` DATE NOT NULL,
  `TransactionCreditDebit` CHAR(1) NOT NULL,
  `TransactionTypeId` INT NOT NULL,
  `Account_AccountId` INT NOT NULL,
  `TransactionValue` DECIMAL(17,2) NULL,
  PRIMARY KEY (`TransactionNr`),
  INDEX `fk_Transaction_TransactionType1_idx` (`TransactionTypeId` ASC) VISIBLE,
  INDEX `fk_Transaction_Account1_idx` (`Account_AccountId` ASC) VISIBLE,
  CONSTRAINT `fk_Transaction_TransactionType`
    FOREIGN KEY (`TransactionTypeId`)
    REFERENCES `TransactionType` (`TransactionTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_Account`
    FOREIGN KEY (`Account_AccountId`)
    REFERENCES `Account` (`AccountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `State`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `State` ;

CREATE TABLE IF NOT EXISTS `State` (
  `StateId` INT NOT NULL,
  `StateCode` CHAR(2) NOT NULL,
  PRIMARY KEY (`StateId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `City` ;

CREATE TABLE IF NOT EXISTS `City` (
  `StateCityId` INT NOT NULL AUTO_INCREMENT,
  `StateId` INT NOT NULL,
  `CityName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`StateCityId`),
  INDEX `fk_City_State_idx` (`StateId` ASC) VISIBLE,
  CONSTRAINT `fk_City_State`
    FOREIGN KEY (`StateId`)
    REFERENCES `State` (`StateId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AddressType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AddressType` ;

CREATE TABLE IF NOT EXISTS `AddressType` (
  `AddressTypeId` INT NOT NULL AUTO_INCREMENT,
  `AddressTypeDescription` VARCHAR(50) NULL,
  PRIMARY KEY (`AddressTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Address` ;

CREATE TABLE IF NOT EXISTS `Address` (
  `AddressId` INT NOT NULL AUTO_INCREMENT,
  `CustomerId` INT NOT NULL,
  `AddressName` VARCHAR(200) NOT NULL,
  `AddressNumber` VARCHAR(50) NOT NULL,
  `AddressComplement` VARCHAR(100) NULL,
  `AddressZipCope` VARCHAR(50) NOT NULL,
  `AddressType` VARCHAR(45) NOT NULL,
  `AddressTypeId` INT NOT NULL,
  `StateCityId` INT NOT NULL,
  INDEX `fk_Address_Customer_idx` (`CustomerId` ASC) VISIBLE,
  PRIMARY KEY (`AddressId`),
  INDEX `fk_Address_AddressType_idx` (`AddressTypeId` ASC) VISIBLE,
  INDEX `fk_Address_City_idx` (`StateCityId` ASC) VISIBLE,
  CONSTRAINT `fk_Address_Customer`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Address_AddressType`
    FOREIGN KEY (`AddressTypeId`)
    REFERENCES `AddressType` (`AddressTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Address_City`
    FOREIGN KEY (`StateCityId`)
    REFERENCES `City` (`StateCityId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
